# Generated by Django 4.2.5 on 2023-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArhetectureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('overview', models.TextField()),
                ('locality', models.CharField(max_length=50)),
                ('sources', models.TextField()),
                ('img_path_1', models.TextField()),
                ('img_name_1', models.CharField(max_length=100)),
                ('img_autor_1', models.CharField(max_length=50)),
                ('img_sourc_1', models.CharField(max_length=50)),
                ('img_path_2', models.TextField()),
                ('img_name_2', models.CharField(max_length=100)),
                ('img_autor_2', models.CharField(max_length=50)),
                ('img_sourc_2', models.CharField(max_length=50)),
                ('img_path_3', models.TextField()),
                ('img_name_3', models.CharField(max_length=100)),
                ('img_autor_3', models.CharField(max_length=50)),
                ('img_sourc_3', models.CharField(max_length=50)),
            ],
        ),
    ]
