# Generated by Django 4.2.5 on 2023-10-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('sourc', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_autor_1',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_autor_2',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_autor_3',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_name_1',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_name_2',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_name_3',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_path_1',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_path_2',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_path_3',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_sourc_1',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_sourc_2',
        ),
        migrations.RemoveField(
            model_name='arhetectureobject',
            name='img_sourc_3',
        ),
        migrations.CreateModel(
            name='ArhetectureImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.image')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arh_image', to='Main.arhetectureobject')),
            ],
            bases=('Main.image',),
        ),
    ]
