# Generated by Django 4.2.5 on 2023-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_arhetectureobject_type_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arhetectureobject',
            name='type_build',
            field=models.CharField(choices=[('v1', 'Замок'), ('v2', 'Ратуша'), ('v2', 'Православный храм'), ('v3', 'Католический храм'), ('v4', 'Синагога'), ('v5', 'Дворец/Усадьба'), ('v6', 'Разное')], max_length=50),
        ),
    ]
