# Generated by Django 4.2.5 on 2023-10-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_arhetectureobject_type_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='arhetectureobject',
            name='type_build',
            field=models.CharField(choices=[('Замок', 'Замок'), ('Ратуша', 'Ратуша'), ('Православный храм', 'Православный храм'), ('Католический храм', 'Католический храм'), ('Синагога', 'Синагога'), ('Дворец/Усадьба', 'Дворец/Усадьба'), ('Разное', 'Разное')], max_length=50),
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.image')),
                ('type_img', models.CharField(choices=[('Изображение', 'Изображение'), ('План/Карта', 'План/Карта')], max_length=50)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_image', to='Main.cityobject')),
            ],
            bases=('Main.image',),
        ),
    ]
