# Generated by Django 4.2.5 on 2023-10-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_cityobject_alter_arhetectureobject_type_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityobject',
            name='x',
            field=models.FloatField(default=5.5),
        ),
        migrations.AddField(
            model_name='cityobject',
            name='y',
            field=models.FloatField(default=5.5),
        ),
    ]
