# Generated by Django 4.2.5 on 2023-10-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_cityobject_x_cityobject_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityobject',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cityobject',
            name='y',
            field=models.FloatField(),
        ),
    ]
