# Generated by Django 4.2.5 on 2023-10-10 16:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_cityobject_x_alter_cityobject_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('overview', ckeditor.fields.RichTextField()),
                ('sources', ckeditor.fields.RichTextField()),
                ('main_image', models.TextField()),
                ('chapter_image', models.TextField()),
            ],
        ),
    ]
