# Generated by Django 4.2.5 on 2023-10-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_artifactobject_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactobject',
            name='main_image',
        ),
        migrations.AddField(
            model_name='artifactobject',
            name='autor_image',
            field=models.CharField(default='fhdfhufh', max_length=50),
        ),
        migrations.AddField(
            model_name='artifactobject',
            name='name_image',
            field=models.CharField(default='fhdfhufh', max_length=100),
        ),
        migrations.AddField(
            model_name='artifactobject',
            name='path_image',
            field=models.TextField(default='fhdfhufh'),
        ),
        migrations.AddField(
            model_name='artifactobject',
            name='sourc_image',
            field=models.CharField(default='fhdfhufh', max_length=100),
        ),
    ]
